version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  build:
    commands:
      - npm install --silent --no-progress -g serverless@1.41.1
      - serverless deploy --stage $env --package $CODEBUILD_SRC_DIR/target/$env -v -r eu-central-1