version: 0.2

phases:
  install:
    commands:
      - npm install --silent --no-progress serverless
      - npm install --silent --no-progress serverless-plugin-export-endpoints
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - mvn package
      - npx sls package --package target/serverless/dev --stage dev -v -r eu-central-1
      - npx sls package --package target/serverless/prod --stage prod -v -r eu-central-1
artifacts:
  files:
    - target/library-api-dev.jar
    - target/serverless/**/*
    - serverless.yml
    - package.json
    - buildspec-deploy-dev.yml
    - buildspec-deploy-prod.yml
    - test/**/*