version: 0.2

phases:
  install:
    commands:
      npm install --silent --no-progress
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - mkdir -p target/stg
      - mkdir target/prod
      - npm run sls package --package target/prod --stage prod -v -r eu-central-1
      - npm run sls package --package target/dev --stage dev -v -r eu-central-1
artifacts:
  files:
    - target/**/*
    - serverless.yml
    - package.json
    - buildspec-deploy.yml