version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  build:
    commands:
      - npm install -g serverless@1.41.1
      - echo "EHV $env"
      - echo "CODEBUILD_SRC_DIR $CODEBUILD_SRC_DIR"
      - ls -la $CODEBUILD_SRC_DIR
      - ls -la $CODEBUILD_SRC_DIR/target
      - serverless deploy --stage $env --package $CODEBUILD_SRC_DIR/target/$env -v -r eu-central-1