version: 0.2

phases:
  install:
    commands:
      npm install --silent --no-progress
    runtime-versions:
      java: openjdk8
  post_build:
    commands:
      - echo Build started on $(date)
      - mvn package
      - mkdir target/serverless
      - mv target/library-api-dev.jar target/serverless
      - npm run sls package --package target/serverless/prod --stage prod -v -r eu-central-1
      - npm run sls package --package target/serverless/dev --stage dev -v -r eu-central-1
      - echo Build completed on $(date)
      - ls -la target
      - ls -la target/serverless
artifacts:
  files:
    - target/serverless/*
    - serverless.yml
    - package.json
    - buildspec-deploy.yml